"use strict";(()=>{var $=Object.defineProperty;var w=(y,u)=>$(y,"name",{value:u,configurable:!0});(globalThis.ffzAddonsWebpackJsonp=globalThis.ffzAddonsWebpackJsonp||[]).push([[738],{4592:(y,u,c)=>{c.r(u),c.d(u,{default:()=>p});var f=w(function(){var t=this,o=t.$createElement,a=t._self._c||o;return a("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[a("header",{staticClass:"tw-mg-y-05"},[t._v(`
			`+t._s(t.t(t.type.i18n,t.type.title))+`
		`)]),t._v(" "),t.type.about?a("div",[a("markdown",{attrs:{source:t.t(t.type.about_i18n?t.type.about_i18n:t.type.i18n+".about",t.type.about)}})],1):t._e(),t._v(" "),t._l(t.badges,function(e){return a("div",{key:e.title},[a("div",{staticClass:"tw-mg-b-05 tw-mg-t-05"},[t._v(t._s(e.title))]),t._v(" "),a("div",{staticClass:"tw-flex tw-flex-wrap"},t._l(e.badges,function(s){return a("div",{key:s.id,staticClass:"ffz-checkbox tw-mg-r-05 tw-mg-b-05"},[a("input",{staticClass:"ffz-checkbox__input",attrs:{id:"badge$"+s.id+"$"+t.value.id,type:"checkbox"},domProps:{checked:t.enabled_badges.indexOf(s.id)!==-1},on:{input:function(l){return t.onChange(s.id,l)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"badge$"+s.id+"$"+t.value.id}},[a("div",{staticClass:"ffz-pn--preview-image ffz-badge tw-mg-x-05 tw-flex-shrink-0",style:{backgroundColor:s.color,backgroundImage:s.styleImage}}),t._v(`
                        `+t._s(s.name)+`
                    `)])])}),0)])}),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+t.value.id,type:"checkbox"},domProps:{checked:Array.isArray(t.value.data.critical)?t._i(t.value.data.critical,null)>-1:t.value.data.critical},on:{change:function(e){var s=t.value.data.critical,l=e.target,r=!!l.checked;if(Array.isArray(s)){var n=null,i=t._i(s,n);l.checked?i<0&&t.$set(t.value.data,"critical",s.concat([n])):i>-1&&t.$set(t.value.data,"critical",s.slice(0,i).concat(s.slice(i+1)))}else t.$set(t.value.data,"critical",r)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
					`+t._s(t.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
				`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
					`+t._s(t.t("addon.prattlenot.score","Score"))+`
				`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+t.value.id,type:"number"},domProps:{value:t.value.data.score},on:{change:function(e){t.$set(t.value.data,"score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})])],2)},"render"),v=[];let m=0;const _={props:["value","type","filters","context"],data(){return{badges:FrankerFaceZ.get().resolve("chat.badges").getSettingsBadges(!0,()=>this.onBadgesLoad()),id:m++}},computed:{enabled_badges(){return Array.isArray(this.value.data.badges)?this.value.data.badges:[]}},methods:{onBadgesLoad(){this.badges=FrankerFaceZ.get().resolve("chat.badges").getSettingsBadges()},onChange(t,o){const a=o.target.checked,e=this.value.data.badges;if(!Array.isArray(e)){a&&(this.value.data.badges=[t]);return}const s=e.indexOf(t);s===-1&&a?e.push(t):s!==-1&&!a&&e.splice(s,1)}}};var d=c(3006),g=(0,d.Z)(_,f,v,!1,null,null,null);const p=g.exports},5461:(y,u,c)=>{c.r(u),c.d(u,{default:()=>p});var f=w(function(){var t=this,o=t.$createElement,a=t._self._c||o;return a("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[a("header",{staticClass:"tw-mg-y-05"},[t._v(`
		`+t._s(t.t(t.type.i18n,t.type.title))+`
	`)]),t._v(" "),t.type.about?a("div",[a("markdown",{attrs:{source:t.t(t.type.about_i18n?t.type.about_i18n:t.type.i18n+".about",t.type.about)}})],1):t._e(),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+t.value.id,type:"checkbox"},domProps:{checked:Array.isArray(t.value.data.critical)?t._i(t.value.data.critical,null)>-1:t.value.data.critical},on:{change:function(e){var s=t.value.data.critical,l=e.target,r=!!l.checked;if(Array.isArray(s)){var n=null,i=t._i(s,n);l.checked?i<0&&t.$set(t.value.data,"critical",s.concat([n])):i>-1&&t.$set(t.value.data,"critical",s.slice(0,i).concat(s.slice(i+1)))}else t.$set(t.value.data,"critical",r)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.score","Score"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+t.value.id,type:"number"},domProps:{value:t.value.data.score},on:{change:function(e){t.$set(t.value.data,"score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})])])},"render"),v=[];let m=0;const _={props:["value","type","filters","context"],data(){return{id:m++}}};var d=c(3006),g=(0,d.Z)(_,f,v,!1,null,null,null);const p=g.exports},2729:(y,u,c)=>{c.r(u),c.d(u,{default:()=>p});var f=w(function(){var t=this,o=t.$createElement,a=t._self._c||o;return a("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[a("header",{staticClass:"tw-mg-y-05"},[t._v(`
		`+t._s(t.t(t.type.i18n,t.type.title))+`
	`)]),t._v(" "),t.type.about?a("div",[a("markdown",{attrs:{source:t.t(t.type.about_i18n?t.type.about_i18n:t.type.i18n+".about",t.type.about)}})],1):t._e(),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"bits$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.bits","Minimum Bits"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.min_bits,expression:"value.data.min_bits",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"bits$"+t.value.id,type:"number"},domProps:{value:t.value.data.min_bits},on:{change:function(e){t.$set(t.value.data,"min_bits",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+t.value.id,type:"checkbox"},domProps:{checked:Array.isArray(t.value.data.critical)?t._i(t.value.data.critical,null)>-1:t.value.data.critical},on:{change:function(e){var s=t.value.data.critical,l=e.target,r=!!l.checked;if(Array.isArray(s)){var n=null,i=t._i(s,n);l.checked?i<0&&t.$set(t.value.data,"critical",s.concat([n])):i>-1&&t.$set(t.value.data,"critical",s.slice(0,i).concat(s.slice(i+1)))}else t.$set(t.value.data,"critical",r)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.score","Score"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+t.value.id,type:"number"},domProps:{value:t.value.data.score},on:{change:function(e){t.$set(t.value.data,"score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})])])},"render"),v=[];let m=0;const _={props:["value","type","filters","context"],data(){return{id:m++}}};var d=c(3006),g=(0,d.Z)(_,f,v,!1,null,null,null);const p=g.exports},6720:(y,u,c)=>{c.r(u),c.d(u,{default:()=>p});var f=w(function(){var t=this,o=t.$createElement,a=t._self._c||o;return a("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[a("header",{staticClass:"tw-mg-y-05"},[t._v(`
		`+t._s(t.t(t.type.i18n,t.type.title))+`
	`)]),t._v(" "),t.type.about?a("div",[a("markdown",{attrs:{source:t.t(t.type.about_i18n?t.type.about_i18n:t.type.i18n+".about",t.type.about)}})],1):t._e(),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"max_emotes$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.max_emotes","Maximum Emotes"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.max_emotes,expression:"value.data.max_emotes",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"max_emotes$"+t.value.id,type:"number"},domProps:{value:t.value.data.max_emotes},on:{change:function(e){t.$set(t.value.data,"max_emotes",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+t.value.id,type:"checkbox"},domProps:{checked:Array.isArray(t.value.data.critical)?t._i(t.value.data.critical,null)>-1:t.value.data.critical},on:{change:function(e){var s=t.value.data.critical,l=e.target,r=!!l.checked;if(Array.isArray(s)){var n=null,i=t._i(s,n);l.checked?i<0&&t.$set(t.value.data,"critical",s.concat([n])):i>-1&&t.$set(t.value.data,"critical",s.slice(0,i).concat(s.slice(i+1)))}else t.$set(t.value.data,"critical",r)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.score","Score"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+t.value.id,type:"number"},domProps:{value:t.value.data.score},on:{change:function(e){t.$set(t.value.data,"score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})])])},"render"),v=[];let m=0;const _={props:["value","type","filters","context"],data(){return{id:m++}}};var d=c(3006),g=(0,d.Z)(_,f,v,!1,null,null,null);const p=g.exports},2790:(y,u,c)=>{c.r(u),c.d(u,{default:()=>p});var f=w(function(){var t=this,o=t.$createElement,a=t._self._c||o;return a("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[a("header",{staticClass:"tw-mg-y-05"},[t._v(`
		`+t._s(t.t(t.type.i18n,t.type.title))+`
	`)]),t._v(" "),t.type.about?a("div",[a("markdown",{attrs:{source:t.t(t.type.about_i18n,t.type.about)}})],1):t._e(),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"hash$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.hash_count","Hash Storage Size"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.hash_count,expression:"value.data.hash_count",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"hash$"+t.value.id,type:"number"},domProps:{value:t.value.data.hash_count},on:{change:function(e){t.$set(t.value.data,"hash_count",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"leven$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.leven_count","Levenshtein Storage Size"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.leven_count,expression:"value.data.leven_count",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"leven$"+t.value.id,type:"number"},domProps:{value:t.value.data.leven_count},on:{change:function(e){t.$set(t.value.data,"leven_count",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"leven_score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.leven_score","Levenshtein Threshold"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.leven_score,expression:"value.data.leven_score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"leven_score$"+t.value.id,type:"number",step:"0.05",min:"0",max:"1"},domProps:{value:t.value.data.leven_score},on:{change:function(e){t.$set(t.value.data,"leven_score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+t.value.id,type:"checkbox"},domProps:{checked:Array.isArray(t.value.data.critical)?t._i(t.value.data.critical,null)>-1:t.value.data.critical},on:{change:function(e){var s=t.value.data.critical,l=e.target,r=!!l.checked;if(Array.isArray(s)){var n=null,i=t._i(s,n);l.checked?i<0&&t.$set(t.value.data,"critical",s.concat([n])):i>-1&&t.$set(t.value.data,"critical",s.slice(0,i).concat(s.slice(i+1)))}else t.$set(t.value.data,"critical",r)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.score","Score"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+t.value.id,type:"number"},domProps:{value:t.value.data.score},on:{change:function(e){t.$set(t.value.data,"score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})])])},"render"),v=[];let m=0;const _={props:["value","type","filters","context"],data(){return{id:m++}}};var d=c(3006),g=(0,d.Z)(_,f,v,!1,null,null,null);const p=g.exports},7144:(y,u,c)=>{c.r(u),c.d(u,{default:()=>p});var f=w(function(){var t=this,o=t.$createElement,a=t._self._c||o;return a("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[a("header",{staticClass:"tw-mg-y-05"},[t._v(`
		`+t._s(t.t(t.type.i18n,t.type.title))+`
	`)]),t._v(" "),t.type.about?a("div",[a("markdown",{attrs:{source:t.t(t.type.about_i18n?t.type.about_i18n:t.type.i18n+".about",t.type.about)}})],1):t._e(),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"limit$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.limit","Limit"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.limit,expression:"value.data.limit",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"limit$"+t.value.id,type:"number"},domProps:{value:t.value.data.limit},on:{change:function(e){t.$set(t.value.data,"limit",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+t.value.id,type:"checkbox"},domProps:{checked:Array.isArray(t.value.data.critical)?t._i(t.value.data.critical,null)>-1:t.value.data.critical},on:{change:function(e){var s=t.value.data.critical,l=e.target,r=!!l.checked;if(Array.isArray(s)){var n=null,i=t._i(s,n);l.checked?i<0&&t.$set(t.value.data,"critical",s.concat([n])):i>-1&&t.$set(t.value.data,"critical",s.slice(0,i).concat(s.slice(i+1)))}else t.$set(t.value.data,"critical",r)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.score","Score"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+t.value.id,type:"number"},domProps:{value:t.value.data.score},on:{change:function(e){t.$set(t.value.data,"score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})])])},"render"),v=[];let m=0;const _={props:["value","type","filters","context"],data(){return{id:m++}}};var d=c(3006),g=(0,d.Z)(_,f,v,!1,null,null,null);const p=g.exports},7728:(y,u,c)=>{c.r(u),c.d(u,{default:()=>a});var f=w(function(){var e=this,s=e.$createElement,l=e._self._c||s;return l("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[l("header",{staticClass:"tw-mg-y-05"},[e._v(`
		`+e._s(e.t(e.type.i18n,e.type.title))+`
	`)]),e._v(" "),e.type.about?l("div",[l("markdown",{attrs:{source:e.t(e.type.about_i18n?e.type.about_i18n:e.type.i18n+".about",e.type.about)}})],1):e._e(),e._v(" "),l("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[l("label",{attrs:{for:"cats$"+e.value.id}},[l("span",{staticClass:"tw-mg-l-1"},[e._v(`
				`+e._s(e.t("addon.prattlenot.categories","Categories"))+`
			`)])]),e._v(" "),l("div",{staticClass:"tw-flex tw-flex-wrap tw-align-items-center"},e._l(e.CATEGORIES,function(r){return l("div",{key:r.value,staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-x-05"},[l("input",{staticClass:"ffz-checkbox__input",attrs:{id:"cat$"+r.value+"$"+e.value.id,type:"checkbox"},domProps:{checked:e.categories.includes(r.label)},on:{input:function(n){return e.onChange("cat",r.label,n)}}}),e._v(" "),l("label",{staticClass:"ffz-checkbox__label",attrs:{for:"cat$"+r.value+"$"+e.value.id}},[e._v(`
					`+e._s(e.t("addon.prattlenot.unicode.cat."+r.value,r.label))+`
				`)])])}),0)]),e._v(" "),l("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[l("label",{attrs:{for:"scripts$"+e.value.id}},[l("span",{staticClass:"tw-mg-l-1"},[e._v(`
				`+e._s(e.t("addon.prattlenot.scripts","Scripts"))+`
			`)])]),e._v(" "),l("div",{staticClass:"tw-flex tw-flex-wrap tw-align-items-center"},e._l(e.SCRIPTS,function(r){return l("div",{key:r,staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-x-05"},[l("input",{staticClass:"ffz-checkbox__input",attrs:{id:"script$"+r+"$"+e.value.id,type:"checkbox"},domProps:{checked:e.scripts.includes(r)},on:{input:function(n){return e.onChange("script",r,n)}}}),e._v(" "),l("label",{staticClass:"ffz-checkbox__label",attrs:{for:"script$"+r+"$"+e.value.id}},[e._v(`
					`+e._s(e.t("addon.prattlenot.unicode.script."+r,r))+`
				`)])])}),0)]),e._v(" "),l("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[l("label",{attrs:{for:"threshold$"+e.value.id}},[l("span",{staticClass:"tw-mg-l-1"},[e._v(`
				`+e._s(e.t("addon.prattlenot.threshold","Threshold"))+`
			`)])]),e._v(" "),l("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:e.value.data.threshold,expression:"value.data.threshold",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"threshold$"+e.value.id,type:"number",min:"0",max:"1",step:"0.05"},domProps:{value:e.value.data.threshold},on:{change:function(r){e.$set(e.value.data,"threshold",e._n(r.target.value))},blur:function(r){return e.$forceUpdate()}}})]),e._v(" "),l("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[l("input",{directives:[{name:"model",rawName:"v-model",value:e.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+e.value.id,type:"checkbox"},domProps:{checked:Array.isArray(e.value.data.critical)?e._i(e.value.data.critical,null)>-1:e.value.data.critical},on:{change:function(r){var n=e.value.data.critical,i=r.target,h=!!i.checked;if(Array.isArray(n)){var C=null,x=e._i(n,C);i.checked?x<0&&e.$set(e.value.data,"critical",n.concat([C])):x>-1&&e.$set(e.value.data,"critical",n.slice(0,x).concat(n.slice(x+1)))}else e.$set(e.value.data,"critical",h)}}}),e._v(" "),l("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+e.value.id}},[l("span",{staticClass:"tw-mg-l-1"},[e._v(`
				`+e._s(e.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
			`)])])]),e._v(" "),l("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[l("label",{attrs:{for:"score$"+e.value.id}},[l("span",{staticClass:"tw-mg-l-1"},[e._v(`
				`+e._s(e.t("addon.prattlenot.score","Score"))+`
			`)])]),e._v(" "),l("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:e.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+e.value.id,type:"number"},domProps:{value:e.value.data.score},on:{change:function(r){e.$set(e.value.data,"score",e._n(r.target.value))},blur:function(r){return e.$forceUpdate()}}})])])},"render"),v=[];const m={L:"Letter",Ll:"Lowercase Letter",Lu:"Uppercase Letter",Lt:"Titlecase Letter",Lm:"Modifier Letter",Lo:"Other Letter",M:"Mark",Mn:"Non-Spacing Mark",Mc:"Spacing Combining Mark",Me:"Enclosing Mark",Z:"Separator",Zs:"Space Separator",Zl:"Line Separator",Zp:"Paragraph Separator",S:"Symbol",Sm:"Math Symbol",Sc:"Currency Symbol",Sk:"Modifier Symbol",So:"Other Symbol",N:"Number",Nd:"Decimal Digit Number",Nl:"Letter Number",No:"Other Number",P:"Punctuation",Pd:"Dash Punctuation",Ps:"Open Punctuation",Pe:"Close Punctuation",Pi:"Initial Punctuation",Pf:"Final Punctuation",Pc:"Connector Punctuation",Po:"Other Punctuation",C:"Other",Cc:"Control",Cf:"Format",Co:"Private Use",Cs:"Surrogate",Cn:"Unassigned"},b=["Common","Arabic","Armenian","Bengali","Bopomofo","Braille","Buhid","Canadian_Aboriginal","Cherokee","Cyrillic","Devanagari","Ethiopic","Georgian","Greek","Gujarati","Gurmukhi","Han","Hangul","Hanunoo","Hebrew","Hiragana","Inherited","Kannada","Katakana","Khmer","Lao","Latin","Limbu","Malayalam","Mongolian","Myanmar","Ogham","Oriya","Runic","Sinhala","Syriac","Tagalog","Tagbanwa","Tai_Le","Tamil","Telugu","Thaana","Thai","Tibetan","Yi"],{deep_copy:_}=FrankerFaceZ.utilities.object;let d=0;const p={props:["value","type","filters","context"],data(){const e=[];for(const[s,l]of Object.entries(m))e.push({value:s,label:l});return{CATEGORIES:e,SCRIPTS:_(b),id:d++}},computed:{categories(){const e=[];if(Array.isArray(this.value.data.terms))for(const s of this.value.data.terms)s&&s.t==="cat"&&e.push(s.v);return e},scripts(){const e=[];if(Array.isArray(this.value.data.terms))for(const s of this.value.data.terms)s&&s.t==="script"&&e.push(s.v);return e}},methods:{onChange(e,s,l){const r=l.target.checked;if(!Array.isArray(this.value.data.terms)){r&&(this.value.data.terms=[{t:e,v:s}]);return}const n=this.value.data.terms;for(let i=0;i<n.length;i++){const h=n[i];if(h&&h.t===e&&h.v===s){r||n.splice(i,1);return}}r&&n.push({t:e,v:s})}}};var t=c(3006),o=(0,t.Z)(p,f,v,!1,null,null,null);const a=o.exports},836:(y,u,c)=>{c.r(u),c.d(u,{default:()=>p});var f=w(function(){var t=this,o=t.$createElement,a=t._self._c||o;return a("section",{staticClass:"tw-flex-grow-1 tw-align-self-start"},[a("header",{staticClass:"tw-mg-y-05"},[t._v(`
		`+t._s(t.t(t.type.i18n,t.type.title))+`
	`)]),t._v(" "),t.type.about?a("div",[a("markdown",{attrs:{source:t.t(t.type.about_i18n?t.type.about_i18n:t.type.i18n+".about",t.type.about)}})],1):t._e(),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"threshold$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.threshold","Threshold"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.threshold,expression:"value.data.threshold",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"threshold$"+t.value.id,type:"number",min:"0",max:"1",step:"0.05"},domProps:{value:t.value.data.threshold},on:{change:function(e){t.$set(t.value.data,"threshold",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center ffz-checkbox tw-mg-y-05 tw-mg-l-3"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.data.critical,expression:"value.data.critical"}],staticClass:"ffz-checkbox__input",attrs:{id:"critical$"+t.value.id,type:"checkbox"},domProps:{checked:Array.isArray(t.value.data.critical)?t._i(t.value.data.critical,null)>-1:t.value.data.critical},on:{change:function(e){var s=t.value.data.critical,l=e.target,r=!!l.checked;if(Array.isArray(s)){var n=null,i=t._i(s,n);l.checked?i<0&&t.$set(t.value.data,"critical",s.concat([n])):i>-1&&t.$set(t.value.data,"critical",s.slice(0,i).concat(s.slice(i+1)))}else t.$set(t.value.data,"critical",r)}}}),t._v(" "),a("label",{staticClass:"ffz-checkbox__label",attrs:{for:"critical$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.critical","Critical (Stop Immediately)"))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-center tw-mg-y-05"},[a("label",{attrs:{for:"score$"+t.value.id}},[a("span",{staticClass:"tw-mg-l-1"},[t._v(`
				`+t._s(t.t("addon.prattlenot.score","Score"))+`
			`)])]),t._v(" "),a("input",{directives:[{name:"model",rawName:"v-model.number.lazy",value:t.value.data.score,expression:"value.data.score",modifiers:{number:!0,lazy:!0}}],staticClass:"tw-flex-grow-1 tw-border-radius-medium tw-font-size-6 tw-mg-x-1 tw-pd-x-1 tw-pd-y-05 ffz-input",attrs:{id:"score$"+t.value.id,type:"number"},domProps:{value:t.value.data.score},on:{change:function(e){t.$set(t.value.data,"score",t._n(e.target.value))},blur:function(e){return t.$forceUpdate()}}})])])},"render"),v=[];let m=0;const _={props:["value","type","filters","context"],data(){return{id:m++}}};var d=c(3006),g=(0,d.Z)(_,f,v,!1,null,null,null);const p=g.exports},3006:(y,u,c)=>{c.d(u,{Z:()=>f});function f(v,m,b,_,d,g,p,t){var o=typeof v=="function"?v.options:v;m&&(o.render=m,o.staticRenderFns=b,o._compiled=!0),_&&(o.functional=!0),g&&(o._scopeId="data-v-"+g);var a;if(p?(a=w(function(l){l=l||this.$vnode&&this.$vnode.ssrContext||this.parent&&this.parent.$vnode&&this.parent.$vnode.ssrContext,!l&&typeof __VUE_SSR_CONTEXT__<"u"&&(l=__VUE_SSR_CONTEXT__),d&&d.call(this,l),l&&l._registeredComponents&&l._registeredComponents.add(p)},"hook"),o._ssrRegister=a):d&&(a=t?function(){d.call(this,(o.functional?this.parent:this).$root.$options.shadowRoot)}:d),a)if(o.functional){o._injectStyles=a;var e=o.render;o.render=w(function(r,n){return a.call(n),e(r,n)},"renderWithStyleInjection")}else{var s=o.beforeCreate;o.beforeCreate=s?[].concat(s,a):[a]}return{exports:v,options:o}}w(f,"normalizeComponent")}}]);})();

//# sourceMappingURL=vue.js.map