"use strict";(()=>{var A=Object.defineProperty;var r=(u,o)=>A(u,"name",{value:o,configurable:!0});(globalThis.ffzAddonsWebpackJsonp=globalThis.ffzAddonsWebpackJsonp||[]).push([[127],{5316:(u,o,v)=>{v.r(o),v.d(o,{default:()=>C});var p=r(function(){var t=this,d=t.$createElement,a=t._self._c||d;return a("div",[a("div",{staticClass:"tw-flex tw-align-items-start"},[a("label",{staticClass:"tw-mg-y-05",attrs:{for:"edit_url"}},[t._v(`
			`+t._s(t.t("setting.actions.url","URL"))+`
		`)]),t._v(" "),a("div",{staticClass:"tw-full-width"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.url,expression:"value.url"}],staticClass:"tw-border-radius-medium tw-font-size-6 tw-full-width ffz-input tw-pd-x-1 tw-pd-y-05 tw-mg-y-05",attrs:{id:"edit_url",placeholder:t.defaults.url},domProps:{value:t.value.url},on:{input:[function(s){s.target.composing||t.$set(t.value,"url",s.target.value)},function(s){return t.$emit("input",t.value)}]}}),t._v(" "),a("div",{staticClass:"tw-c-text-alt-2 tw-mg-b-1"},[t._v(`
				`+t._s(t.t("setting.actions.variables","Available Variables: {vars}",{vars:t.vars}))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-start"},[a("label",{staticClass:"tw-mg-y-05",attrs:{for:"action_id"}},[t._v("Action ID")]),t._v(" "),a("div",{staticClass:"tw-full-width"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.actionId,expression:"value.actionId"}],staticClass:"tw-border-radius-medium tw-font-size-6 tw-full-width ffz-input tw-pd-x-1 tw-pd-y-05 tw-mg-y-05",attrs:{id:"action_id",placeholder:t.defaults.actionId},domProps:{value:t.value.actionId},on:{input:[function(s){s.target.composing||t.$set(t.value,"actionId",s.target.value)},function(s){return t.$emit("input",t.value)}]}}),t._v(" "),a("div",{staticClass:"tw-c-text-alt-2 tw-mg-b-1"},[t._v(`
				`+t._s(t.t("setting.actions.variables","Available Variables: {vars}",{vars:t.vars}))+`
			`)])])]),t._v(" "),a("div",{staticClass:"tw-flex tw-align-items-start"},[a("label",{staticClass:"tw-mg-y-05",attrs:{for:"payload_body"}},[t._v("Payload")]),t._v(" "),a("div",{staticClass:"tw-full-width"},[a("input",{directives:[{name:"model",rawName:"v-model",value:t.value.payload,expression:"value.payload"}],staticClass:"tw-border-radius-medium tw-font-size-6 tw-full-width ffz-input tw-pd-x-1 tw-pd-y-05 tw-mg-y-05",attrs:{id:"payload_body",placeholder:t.defaults.payload},domProps:{value:t.value.payload},on:{input:[function(s){s.target.composing||t.$set(t.value,"payload",s.target.value)},function(s){return t.$emit("input",t.value)}]}}),t._v(" "),a("div",{staticClass:"tw-c-text-alt-2 tw-mg-b-1"},[t._v(`
				`+t._s(t.t("setting.actions.variables","Available Variables: {vars}",{vars:t.vars}))+`
			`)]),t._v(" "),a("div",{staticClass:"tw-c-text-alt-2 tw-mg-b-1"},[t._v(`
				`+t._s(t.t("setting.actions.formats","Available Formatters: {fmts}",{fmts:t.fmts}))+`
			`)])])])])},"render"),w=[];const g={props:["value","defaults","vars","fmts"]};function b(t,d,a,s,n,f,c,y){var e=typeof t=="function"?t.options:t;d&&(e.render=d,e.staticRenderFns=a,e._compiled=!0),s&&(e.functional=!0),f&&(e._scopeId="data-v-"+f);var l;if(c?(l=r(function(i){i=i||this.$vnode&&this.$vnode.ssrContext||this.parent&&this.parent.$vnode&&this.parent.$vnode.ssrContext,!i&&typeof __VUE_SSR_CONTEXT__<"u"&&(i=__VUE_SSR_CONTEXT__),n&&n.call(this,i),i&&i._registeredComponents&&i._registeredComponents.add(c)},"hook"),e._ssrRegister=l):n&&(l=y?function(){n.call(this,(e.functional?this.parent:this).$root.$options.shadowRoot)}:n),l)if(e.functional){e._injectStyles=l;var $=e.render;e.render=r(function(z,m){return l.call(m),$(z,m)},"renderWithStyleInjection")}else{var _=e.beforeCreate;e.beforeCreate=_?[].concat(_,l):[l]}return{exports:t,options:e}}r(b,"normalizeComponent");var h=b(g,p,w,!1,null,null,null);const C=h.exports}}]);})();

//# sourceMappingURL=vue.js.map