github.com:
    users:
        svelli11:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: svelli11
