"use strict";(()=>{var g=Object.defineProperty;var c=(f,l)=>g(f,"name",{value:l,configurable:!0});(globalThis.ffzWebpackJsonp=globalThis.ffzWebpackJsonp||[]).push([[8586],{54337:(f,l,n)=>{n.r(l),n.d(l,{default:()=>d});var _=c(function(){var t=this,o=t.$createElement,e=t._self._c||o;return e("div",{staticClass:"ffz-override-editor tw-c-background-base tw-c-text-base tw-pd-05 tw-pd-l-1"},[e("div",{staticClass:"tw-flex tw-align-items-center tw-pd-b-05 tw-border-b tw-mg-b-05"},[e("div",{staticClass:"tw-flex-grow-1"},[t._v(`
			`+t._s(t.t("chat.overrides.editing","Editing {user.login}...",{user:t.user}))+`
		`)]),t._v(" "),e("button",{staticClass:"tw-mg-l-05 tw-button tw-button--text",on:{click:t.close}},[e("span",{staticClass:"tw-button__text ffz-i-window-close"})])]),t._v(" "),e("div",{staticClass:"tw-flex tw-align-items-center"},[e("label",{staticClass:"tw-mg-r-1",attrs:{for:"user-name"}},[t._v(`
			`+t._s(t.t("chat.overrides.name","Name"))+`
		`)]),t._v(" "),e("input",{ref:"name",staticClass:"tw-border-radius-medium tw-font-size-6 tw-pd-x-1 tw-pd-y-05 ffz-input tw-flex-grow-1",attrs:{id:"user-name"},domProps:{value:t.name},on:{change:t.updateName}}),t._v(" "),t.originalName?e("button",{staticClass:"tw-mg-l-05 tw-button tw-button--text ffz-il-tooltip__container",on:{click:t.setOriginalName}},[e("span",{staticClass:"tw-button__text ffz-i-plus"}),t._v(" "),e("div",{staticClass:"ffz-il-tooltip ffz-il-tooltip--down ffz-il-tooltip--align-right"},[t._v(`
				`+t._s(t.t("setting.set-to-current","Set to Current"))+`
			`)])]):t._e(),t._v(" "),e("button",{staticClass:"tw-mg-l-05 tw-button tw-button--text ffz-il-tooltip__container",class:{"tw-button--disabled":t.name==null},on:{click:t.clearName}},[e("span",{staticClass:"tw-button__text ffz-i-cancel"}),t._v(" "),e("div",{staticClass:"ffz-il-tooltip ffz-il-tooltip--down ffz-il-tooltip--align-right"},[t._v(`
				`+t._s(t.t("setting.reset","Reset to Default"))+`
			`)])])]),t._v(" "),e("div",{staticClass:"tw-flex tw-align-items-center"},[e("label",{staticClass:"tw-mg-r-1",attrs:{for:"user-color"}},[t._v(`
			`+t._s(t.t("chat.overrides.color","Color"))+`
		`)]),t._v(" "),e("color-picker",{ref:"color",attrs:{id:"user-color",alpha:!1,nullable:!0,value:t.editColor},on:{input:t.updateColor}}),t._v(" "),t.originalColor?e("button",{staticClass:"tw-mg-l-05 tw-button tw-button--text ffz-il-tooltip__container",on:{click:t.setOriginalColor}},[e("span",{staticClass:"tw-button__text ffz-i-plus"}),t._v(" "),e("div",{staticClass:"ffz-il-tooltip ffz-il-tooltip--down ffz-il-tooltip--align-right"},[t._v(`
				`+t._s(t.t("setting.set-to-current","Set to Current"))+`
			`)])]):t._e(),t._v(" "),e("button",{staticClass:"tw-mg-l-05 tw-button tw-button--text ffz-il-tooltip__container",class:{"tw-button--disabled":t.color==null},on:{click:t.clearColor}},[e("span",{staticClass:"tw-button__text ffz-i-cancel"}),t._v(" "),e("div",{staticClass:"ffz-il-tooltip ffz-il-tooltip--down ffz-il-tooltip--align-right"},[t._v(`
				`+t._s(t.t("setting.reset","Reset to Default"))+`
			`)])])],1)])},"render"),a=[],r=n(46949);const p={data(){return this.$vnode.data},computed:{editColor(){return this.color?this.color:""}},created(){this.updateName=(0,r.debounce)(this.updateName,250),this.updateColor=(0,r.debounce)(this.updateColor,250)},updated(){this.updateTip()},methods:{setOriginalName(){this.name=this.originalName,this.setName(this.name)},setOriginalColor(){this.color=this.originalColor,this.setColor(this.color)},clearName(){this.name=null,this.deleteName()},updateName(){const t=this.$refs.name.value;if(t==null||!t.length){this.clearName();return}this.name=t,this.setName(t)},clearColor(){this.color=null,this.deleteColor()},updateColor(t){if(t==null||!t.length){this.clearColor();return}this.color=t,this.setColor(t)}}};var s=n(72934),u=(0,s.Z)(p,_,a,!1,null,null,null);const d=u.exports},72934:(f,l,n)=>{n.d(l,{Z:()=>_});function _(a,r,v,p,s,u,d,t){var o=typeof a=="function"?a.options:a;r&&(o.render=r,o.staticRenderFns=v,o._compiled=!0),p&&(o.functional=!0),u&&(o._scopeId="data-v-"+u);var e;if(d?(e=c(function(i){i=i||this.$vnode&&this.$vnode.ssrContext||this.parent&&this.parent.$vnode&&this.parent.$vnode.ssrContext,!i&&typeof __VUE_SSR_CONTEXT__<"u"&&(i=__VUE_SSR_CONTEXT__),s&&s.call(this,i),i&&i._registeredComponents&&i._registeredComponents.add(d)},"hook"),o._ssrRegister=e):s&&(e=t?function(){s.call(this,(o.functional?this.parent:this).$root.$options.shadowRoot)}:s),e)if(o.functional){o._injectStyles=e;var w=o.render;o.render=c(function(C,m){return e.call(m),w(C,m)},"renderWithStyleInjection")}else{var h=o.beforeCreate;o.beforeCreate=h?[].concat(h,e):[e]}return{exports:a,options:o}}c(_,"normalizeComponent")}}]);})();

//# sourceMappingURL=overrides.js.map