"use strict";(()=>{var b=Object.defineProperty;var h=(v,i)=>b(v,"name",{value:i,configurable:!0});(globalThis.ffzAddonsWebpackJsonp=globalThis.ffzAddonsWebpackJsonp||[]).push([[366],{6247:(v,i,l)=>{l.r(i),l.d(i,{default:()=>s});var f=h(function(){var t=this,o=t.$createElement,n=t._self._c||o;return n("div",{staticClass:"ffz--widget ffz--text-box",class:{inherits:t.isInherited,default:t.isDefault}},[n("div",{staticClass:"tw-flex tw-align-items-center"},[n("label",{attrs:{for:t.item.full_key}},[t._v(`
			`+t._s(t.t(t.item.i18n_key,t.item.title))+`
			`),t.unseen?n("span",{staticClass:"tw-pill"},[t._v(t._s(t.t("setting.new","New")))]):t._e()]),t._v(" "),n("div",{staticClass:"ffz--search-avatar tw-mg-r-05"},[n("figure",{staticClass:"ffz-avatar ffz-avatar--size-30"},[n("div",{staticClass:"tw-border-radius-rounded tw-overflow-hidden"},[t.current?n("img",{staticClass:"ffz-avatar__img tw-image",attrs:{alt:t.current.displayName,src:t.current.profileImageURL}}):t._e()])])]),t._v(" "),n("autocomplete",{attrs:{"input-id":t.item.full_key,items:t.fetchUsers,value:t.search,placeholder:t.search,"suggest-on-focus":!0,"escape-to-clear":!1},on:{selected:t.onSelected},scopedSlots:t._u([{key:"default",fn:function(a){return[n("div",{staticClass:"tw-pd-x-1 tw-pd-y-05"},[n("div",{staticClass:"tw-card tw-relative"},[n("div",{staticClass:"tw-align-items-center tw-flex tw-flex-nowrap tw-flex-row"},[n("div",{staticClass:"ffz-card-img ffz-card-img--size-3 tw-flex-shrink-0 tw-overflow-hidden"},[n("aspect",{attrs:{ratio:1}},[n("img",{staticClass:"tw-image",attrs:{alt:a.item.displayName,src:a.item.profileImageURL}})])],1),t._v(" "),n("div",{staticClass:"tw-card-body tw-overflow-hidden tw-relative"},[n("p",{staticClass:"tw-pd-x-1"},[t._v(t._s(a.item.displayName))])])])])])]}}])}),t._v(" "),t.source&&t.source!==t.profile?n("button",{staticClass:"tw-mg-l-05 tw-button tw-button--text",on:{click:function(a){t.context.currentProfile=t.source}}},[n("span",{staticClass:"tw-button__text ffz-i-right-dir"},[t._v(`
				`+t._s(t.sourceDisplay)+`
			`)])]):t._e(),t._v(" "),t.has_value?n("button",{staticClass:"tw-mg-l-05 tw-button tw-button--text ffz-il-tooltip__container",on:{click:t.clear}},[n("span",{staticClass:"tw-button__text ffz-i-cancel"}),t._v(" "),n("div",{staticClass:"ffz-il-tooltip ffz-il-tooltip--down ffz-il-tooltip--align-right"},[t._v(`
				`+t._s(t.t("setting.reset","Reset to Default"))+`
			`)])]):t._e()],1),t._v(" "),t.item.description?n("section",{staticClass:"tw-c-text-alt-2"},[n("markdown",{attrs:{source:t.t(t.item.desc_i18n_key||t.item.i18n_key+".description",t.item.description)}})],1):t._e(),t._v(" "),t.item.extra?n("section",[n(t.item.extra.component,{tag:"component",attrs:{context:t.context,item:t.item}})],1):t._e()])},"render"),r=[];const{debounce:_,deep_copy:d}=FrankerFaceZ.utilities.object,u={mixins:[FrankerFaceZ.get().resolve("main_menu").SettingMixin],props:["item","context"],data(){return{current:null,loaded_id:null}},computed:{search(){return this.current&&this.current.displayName},hasChannel(){return this.current!=null}},watch:{value(){this.cacheUser()}},created(){this.td=this.context.getFFZ().resolve("site.twitch_data"),this.cacheUser=_(this.cacheUser,50)},beforeDestroy(){this.td=null,this.cacheUser=null},mounted(){this.cacheUser()},methods:{async cacheUser(){if(this.loaded_id===this.value||(this.current=null,this.loaded_id=this.value,!this.loaded_id))return;const t=await this.td.getUser(this.loaded_id);t?this.current=d(t):this.current=null},async fetchUsers(t){const o=await this.td.getMatchingUsers(t);return!o||!o.items?[]:d(o.items)},onSelected(t){this.current=t;const o=t&&t.id;this.set(o)}}};var e=l(3006),p=(0,e.Z)(u,f,r,!1,null,null,null);const s=p.exports},2945:(v,i,l)=>{l.r(i),l.d(i,{default:()=>u});var f=h(function(){var e=this,p=e.$createElement,s=e._self._c||p;return s("div",[e.shouldBeActive?s("div",{staticClass:"tw-flex"},[s("div",{staticClass:"tw-flex tw-flex-column tw-justify-content-center tw-pd-x-1 tw-pd-y-05 tw-c-background-base tw-border-radius-large tw-mg-r-1 tw-mg-b-1"},[s("p",{staticClass:"tw-c-text-base tw-font-size-4"},[e._v(`
				`+e._s(e.isActive)+`
			`)]),e._v(" "),s("p",{staticClass:"tw-c-text-alt-2 tw-font-size-6"},[e._v(`
				`+e._s(e.t("addon.poll-shim.active","Active"))+`
			`)])]),e._v(" "),s("div",{staticClass:"tw-flex tw-flex-column tw-justify-content-center tw-pd-x-1 tw-pd-y-05 tw-c-background-base tw-border-radius-large tw-mg-r-1 tw-mg-b-1"},[s("p",{staticClass:"tw-c-text-base tw-font-size-4"},[e._v(`
				`+e._s(e.channel?e.channel.displayName:"null")+`
			`)]),e._v(" "),s("p",{staticClass:"tw-c-text-alt-2 tw-font-size-6"},[e._v(`
				`+e._s(e.t("addon.poll-shim.channel","Channel"))+`
			`)])]),e._v(" "),s("div",{staticClass:"tw-flex tw-flex-column tw-justify-content-center tw-pd-x-1 tw-pd-y-05 tw-c-background-base tw-border-radius-large tw-mg-r-1 tw-mg-b-1"},[s("p",{staticClass:"tw-c-text-base tw-font-size-4"},[e._v(`
				`+e._s(e.hasPubSub?e.t("addon.poll-shim.connected","Connected"):e.t("addon.poll-shim.disconnected","Disconnected"))+`
			`)]),e._v(" "),s("p",{staticClass:"tw-c-text-alt-2 tw-font-size-6"},[e._v(`
				`+e._s(e.t("addon.poll-shim.pubsub","PubSub"))+`
			`)])]),e._v(" "),s("div",{staticClass:"tw-flex tw-flex-column tw-justify-content-center tw-pd-x-1 tw-pd-y-05 tw-c-background-base tw-border-radius-large tw-mg-r-1 tw-mg-b-1"},[s("p",{staticClass:"tw-c-text-base tw-font-size-4"},[e._v(`
				`+e._s(e.isAuthed?e.t("addon.poll-shim.authed","Authorized"):e.hasWS?e.t("addon.poll-shim.connected","Connected"):e.t("addon.poll-shim.disconnected","Disconnected"))+`
			`)]),e._v(" "),s("p",{staticClass:"tw-c-text-alt-2 tw-font-size-6"},[e._v(`
				`+e._s(e.t("addon.poll-shim.ws","WebSocket"))+`
			`)])]),e._v(" "),s("div",{staticClass:"tw-flex tw-flex-column tw-justify-content-center tw-pd-x-1 tw-pd-y-05 tw-c-background-base tw-border-radius-large tw-mg-r-1 tw-mg-b-1"},[s("p",{staticClass:"tw-c-text-base tw-font-size-4"},[e._v(`
				`+e._s(e.polls.length)+`
			`)]),e._v(" "),s("p",{staticClass:"tw-c-text-alt-2 tw-font-size-6"},[e._v(`
				`+e._s(e.t("addon.poll-shim.polls","Active Polls"))+`
			`)])])]):s("div",[e._v(`
		`+e._s(e.t("addon.poll-shim.inactive","Poll-Shim is currently inactive. Poll-Shim only runs on the dashboard or your own pop-out chat. Alternatively, if you have set a channel override, Poll-Shim will only run on that channel's dashboard or pop-out chat."))+`
	`)]),e._v(" "),e.shouldBeActive&&!e.hasPoll?s("div",{staticClass:"tw-background-alt-2 tw-border tw-c-border-error tw-pd-1"},[e._v(`
		`+e._s(e.t("addon.poll-shim.no-poll","The channel is not an affiliate or partner and cannot run polls."))+`
	`)]):e.shouldBeActive&&e.self&&!e.canPoll?s("div",{staticClass:"tw-background-alt-2 tw-border tw-pd-1"},[e._v(`
		`+e._s(e.t("addon.poll-shim.cannot-poll","You are not a moderator of this channel and cannot create polls."))+`
	`)]):e._e()])},"render"),r=[];const d={props:["item","context"],data(){return{channel:null,self:null,shouldBeActive:!1,isActive:!1,hasPubSub:!1,hasWS:!1,isAuthed:!1,polls:[]}},computed:{hasPoll(){const e=this.channel?.roles||{};return e.isAffiliate||e.isPartner},canPoll(){return this.hasPoll&&this.self?.isModerator}},created(){this.item.on(":update",this.handleUpdate,this),this.handleUpdate()},destroyed(){this.item.off(":update",this.handleUpdate,this)},methods:{handleUpdate(){this.shouldBeActive=this.item.shouldBeActive(),this.isActive=this.item.isActive(),this.hasPubSub=this.item.hasPubSub(),this.hasWS=this.item.hasWS(),this.isAuthed=this.item.isAuthed(),this.polls=Array.from(this.item.getPolls()),this.item.getChannel().then(e=>this.channel=e),this.item.getSelf().then(e=>this.self=e)}}};var w=l(3006),c=(0,w.Z)(d,f,r,!1,null,null,null);const u=c.exports},3006:(v,i,l)=>{l.d(i,{Z:()=>f});function f(r,_,d,w,c,u,e,p){var s=typeof r=="function"?r.options:r;_&&(s.render=_,s.staticRenderFns=d,s._compiled=!0),w&&(s.functional=!0),u&&(s._scopeId="data-v-"+u);var t;if(e?(t=h(function(a){a=a||this.$vnode&&this.$vnode.ssrContext||this.parent&&this.parent.$vnode&&this.parent.$vnode.ssrContext,!a&&typeof __VUE_SSR_CONTEXT__<"u"&&(a=__VUE_SSR_CONTEXT__),c&&c.call(this,a),a&&a._registeredComponents&&a._registeredComponents.add(e)},"hook"),s._ssrRegister=t):c&&(t=p?function(){c.call(this,(s.functional?this.parent:this).$root.$options.shadowRoot)}:c),t)if(s.functional){s._injectStyles=t;var o=s.render;s.render=h(function(g,m){return t.call(m),o(g,m)},"renderWithStyleInjection")}else{var n=s.beforeCreate;s.beforeCreate=n?[].concat(n,t):[t]}return{exports:r,options:s}}h(f,"normalizeComponent")}}]);})();

//# sourceMappingURL=vue.js.map